- name: create deployments and services
  hosts: kube
  become_user: ubuntu
  become_method: sudo

  tasks:

  - name: create the depolyments and services
    command: kubectl apply -f deployments-services.yml
    args: 
       chdir: /home/ubuntu/cluster

  - name: restart the nginx app deployment
    command: kubectl rollout restart deployment nginx-app