- name: build docker image and push it to dockr hub
  hosts: local
  become_user: marlo
  

  tasks:
  - name: build image
    command: docker build -t reactjs-pipeline .
    args:
       chdir: /home/marlo/devops/nginx

  - name: tag the image
    command: docker tag reactjs-pipeline gerardomarlo/reactjs-pipeline:latest


  - name: push the built image to dockerhub
    command: docker push gerardomarlo/reactjs-pipeline:latest


  - name: delete the built image and the taged one
    command: docker rmi reactjs-pipeline gerardomarlo/reactjs-pipeline:latest